version: '3.8'

services:

  web:
    image: junnie082/scoopadive:latest
    container_name: scoopadive_web
    command: >
      sh -c "
      python manage.py migrate &&
      gunicorn scoopadive.wsgi:application --bind 0.0.0.0:8000
      "
    environment:
      GOOGLE_CLIENT_ID: "${GOOGLE_CLIENT_ID}"
      GOOGLE_CLIENT_SECRET: "${GOOGLE_CLIENT_SECRET}"
      GOOGLE_REDIRECT: "${GOOGLE_REDIRECT}"
      GOOGLE_CALLBACK_URI: "${GOOGLE_CALLBACK_URI}"

      DB_NAME: "${DB_NAME}"
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_HOST: "${DB_HOST}"
      DB_PORT: "${DB_PORT}"

    ports:
      - "8000:8000"
    volumes:
      - static_volume:/scoopadive/staticfiles
    depends_on:
      - db
    networks:
      - scoopadive_network

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /home/ubuntu/Backend/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /home/ubuntu/Frontend/dist:/usr/share/nginx/html:ro
      - static_volume:/scoopadive/staticfiles
    depends_on:
      - web
    networks:
      - scoopadive_network

  db:
    image: postgres:13
    container_name: scoopadive_db
    environment:
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - scoopadive_network

volumes:
  postgres_data:
  static_volume:

networks:
  scoopadive_network:
