name: Scoopadive Deploy to Lightsail

on:
  push:
    branches:
      - deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/scoopadive:latest
          build-args: |
            BUILDKIT_INLINE_CACHE=1
          no-cache: true

      - name: SSH and deploy using docker-compose
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.LIGHTSAIL_HOST }}
          username: ubuntu
          key: ${{ secrets.LIGHTSAIL_SSH_KEY }}

          script: |
            echo "==> 이동: /home/ubuntu/Backend"
            cd /home/ubuntu/Backend

            echo "==> 환경변수 파일 생성 (.env)"
            cat <<EOF > .env
            GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}
            GOOGLE_REDIRECT=${{ secrets.GOOGLE_REDIRECT }}
            GOOGLE_CALLBACK_URI=${{ secrets.GOOGLE_CALLBACK_URI }}
            GOOGLE_SECRET=${{ secrets.GOOGLE_SECRET }}

            WP_CLIENT_ID=${{ secrets.WP_CLIENT_ID }}
            WP_CLIENT_SECRET=${{ secrets.WP_CLIENT_SECRET }}
            WP_REDIRECT_URI=${{ secrets.WP_REDIRECT_URI }}
            
            DB_NAME=${{ secrets.DB_NAME }}
            DB_USER=${{ secrets.DB_USER }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            DB_HOST=${{ secrets.DB_HOST }}
            DB_PORT=${{ secrets.DB_PORT }}

            SECRET_KEY=${{ secrets.SECRET_KEY }}
            EOF

            echo "==> 최신 이미지 Pull"
            sudo docker-compose pull web
            
            echo "==> 기존 컨테이너 중지 및 제거"
            sudo docker-compose down
            
            echo "==> 최신 이미지 기반 컨테이너 다시 실행"
            sudo docker-compose up -d

            echo "==> 마이그레이션 실행"
            sudo docker-compose exec -T web python manage.py migrate

            echo "✅ 배포 완료!"
